<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
	  <TargetFramework>net8.0-windows</TargetFramework>
	  <OutputType>WinExe</OutputType>
	  <RootNamespace>RichIUriStreamProviderExample</RootNamespace>
	  <AssemblyName>RichIUriStreamProviderExample</AssemblyName>
	  <UseWindowsForms>true</UseWindowsForms>
	  <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
	  <GenerateManifests>false</GenerateManifests>
    </PropertyGroup>
    <ItemGroup>
        <Import Include="System.Drawing" />
        <Import Include="System.Windows.Forms" />
    </ItemGroup>
    <ItemGroup>
	    <Content Include="TestDocs\image0.bmp">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    </Content>
        <Content Include="TestDocs\test.html">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
        <PackageReference Include="DevExpress.RichEdit.Export" Version="24.2.*" />
        <PackageReference Include="DevExpress.Document.Processor" Version="24.2.*" />
        <PackageReference Include="DevExpress.Win.RichEdit" Version="24.2.*" />
	    <PackageReference Include="System.Linq" Version="4.3.0" />
    </ItemGroup>
</Project>